### PR TITLE
Add tests for `ProxyRequest`

### PR DESCRIPTION
**Pull request by KotlinIsland**
Added some tests for `ProxyRequest` using Kotlin and `kotlin-test` with JUnitPlatform(JUnit5)

### CODE REVIEW

**Comment by Zeckie** [comment]
Do you need some help converting this to Java + JUnit?

**Comment by KotlinIsland** [comment]
I noticed that the version check was broken on java 8, so I fixed that, also cleaned up the definition of the minjava task to be more idiomatic, 

> Do you need some help converting this to Java + JUnit?

We don't worry about that, the compiler converts it to Java and JUnit already.

One question, why are we using toolchains conditionally? That seems really strange, and adds a lot of complexity for no reason.
Also the `testsMinJava` task will always set up the toolchain anyway.

**Comment by KotlinIsland** [comment]
if we just always used a toolchain we could replace 
```kt
val minimumJavaVersion = JavaVersion.VERSION_1_9

if (JavaVersion.current() < minimumJavaVersion) {
    kotlin {
        jvmToolchain {
            (this as JavaToolchainSpec).languageVersion.set(JavaLanguageVersion.of(minimumJavaVersion.majorVersion))
        }
    }
} else {
    if (JavaVersion.current() > JavaVersion.VERSION_1_9) {
        // Compile for minimum supported java version
        // skip for java 9 due to https://bugs.openjdk.java.net/browse/JDK-8139607
        tasks.withType<JavaCompile> {
            options.release.set(minimumJavaVersion.majorVersion.toInt())
        }
        tasks.withType<KotlinCompile> {
            kotlinOptions.jvmTarget = minimumJavaVersion.majorVersion.takeUnless { it == "8" } ?: "1.8"
        }
    }

    tasks.test {
        dependsOn(testsMinJava)
    }
}

// Test on minimum supported java version
val testsMinJava by tasks.registering(Test::class) {
    group = "verification"
    javaLauncher.set(javaToolchains.launcherFor {
        languageVersion.set(JavaLanguageVersion.of(minimumJavaVersion.majorVersion))
    })
}
```

with:
```kt
kotlin {
    jvmToolchain {
        (this as JavaToolchainSpec).languageVersion.set(JavaLanguageVersion.of(9))
    }
}
```

**Comment by Zeckie** [comment]
> I noticed that the version check was broken on java 8, so I fixed that, also cleaned up the definition of the minjava task to be more idiomatic(and set the group).

I'd already fixed that in https://github.com/Zeckie/ProxyAuth/pull/33 (https://github.com/Zeckie/ProxyAuth/pull/33/commits/a3f5c288cbcda8099afbd8ce14d96aeb6c22f42b) - incl running a CI build using Java 8.

> One question, why are we using toolchains conditionally? That seems really strange, and adds a lot of complexity for no reason. Also the `testsMinJava` task will always set up the toolchain anyway.

The current code allows ProxyAuth to be compiled, tested (except `testsMinJava` task) and run using the users supplied jvm, as long as it is compatible (ie. Java 9 or later). Using toolchain unconditionally would force it to download a JVM in cases where it isn't needed. Some corporate environments require all executables run to be whitelisted, so using the already installed JVM would be a lot easier.

**Comment by Zeckie** [comment]
> > Do you need some help converting this to Java + JUnit?
> 
> We don't worry about that, the compiler converts it to Java and JUnit already.
> 
It looks like an imposter to me (java tests don't need dependency `testImplementation(kotlin("test"))`)

**Comment by KotlinIsland** [comment]
> Using toolchain unconditionally would force it to download a JVM in cases where it isn't needed.

The current implementation will unconditionally download the toolchain.

**Comment by KotlinIsland** [comment]
> It looks like an imposter to me

Those tests could just use JUnit directly, but I don't see any issues with `kotlin-test`

**Comment by Zeckie** [comment]
Added invalid `label`, as this PR will not be merged while the tests are still in Kotlin

**Comment by KotlinIsland** [comment]
You said that tests in Kotlin would be fine. If you wanna change your mind then I'm not interested.

**Pull request closed without merging**
